defaults:
  - _self_
  - dataset: lenscript_nofirstframe
  - diffuser: director_edm_lenscript_nofirstframe
  - compnode: 1g_1n

timestamp: ${now:%Y-%m-%d-%H-%M-%S}

outdir: null
entity: null
project_name: "director_custom"
results_dir: ./results
data_dir: ./lenscript
xp_name: "director_incontext_lenscript"
metric_dir: ./metrics_lenscript
log_dir: ${results_dir}/${xp_name}/${timestamp}
checkpoint_path: null

seed: 42
save_and_sample_every: 64
num_train_epochs: 1536
log_wandb: true
batch_size: 512

trainer:
  _partial_: true
  _target_: lightning.Trainer
  accelerator: cuda
  strategy: auto
  devices: [1]
  max_epochs: ${num_train_epochs}
  precision: 16-mixed
  check_val_every_n_epoch: 64
  num_sanity_val_steps: 0

hydra:
  run:
    dir: ./${results_dir}/${xp_name}/${timestamp}