defaults:
  - dataset: lenscript
  - diffuser: director_edm_lenscript
  - compnode: cpu
  - _self_

timestamp: ${now:%Y-%m-%d-%H-%M-%S}

outdir: null
entity: null
project_name: "director_custom"
results_dir: ./results
data_dir: ./lenscript
xp_name: ${diffuser.loss.name}-${diffuser.network.module.name}-${dataset.name}
log_dir: ${results_dir}/${xp_name}/${timestamp}
checkpoint_path: /data/DIRECTOR/checkpoints/lenscript_incontext/director_incontext_lenscript_epoch=1087.ckpt

seed: 42
save_and_sample_every: 64
num_train_epochs: 257
log_wandb: true
batch_size: 64

hydra:
  run:
    dir: ./${results_dir}/${xp_name}/${timestamp}